### ISSUE TITLE
Library for Debian Bullseye

### ISSUE THREAD

**Issue by stluc** [DEWETRON/pyDmdReader#17]
Would it be possible to also have the library for Bullseye version of Debian?

**Comment by matthiasstraka** [comment]
We will prepare an official library for the next release, in the meanwhile you can use this intermediate build (unzip and install .deb file)
[dewetron-dmd-reader-api_6.5.0.0-bullseye_amd64.deb.zip](https://github.com/DEWETRON/pyDmdReader/files/11746555/dewetron-dmd-reader-api_6.5.0.0-bullseye_amd64.deb.zip)

**Comment by glaure** [comment]
Fixed with v0.7.0
