### ISSUE TITLE
Do you have Ubuntu Release?

### ISSUE THREAD

**Issue by wsf1990** [DEWETRON/pyDmdReader#2]
Do you have Ubuntu Release? Like version 18.04 or 20.04?Thanks!

**Comment by glaure** [comment]
I will provide one!

Thank you for asking!

**Comment by glaure** [comment]
[dewetron-dmd-reader-api_6.0.0ubuntu2004-focal_amd64.deb](https://github.com/DEWETRON/pyDmdReader/releases/download/v0.3.0/dewetron-dmd-reader-api_6.0.0ubuntu2004-focal_amd64.deb)
is now available.
